"""20 个“看图 → 事件 → 记忆 → 回忆”场景案例（任务书 §10 第7条）。

每条案例 = 一张图 + 模型理解结果 + 发生时间 + 用户提问 + 期望答案要点。
默认用 Mock 模型跑（秒级、确定性）；
PAI_REAL=1 时换真模型跑全量（见 test_scenarios.py）。
"""
from __future__ import annotations

SCENARIOS: list[dict] = [
    {
        "name": "01-刚才写作业",
        "when": "recent",
        "understanding": {
            "scene": "书房书桌",
            "activity": "在写数学作业",
            "objects": ["作业本", "铅笔", "台灯"],
            "description": "用户坐在书桌前写数学作业",
            "importance": 0.5,
            "facts": ["用户最近在认真学数学"],
        },
        "query": "刚才我在干什么",
        "expect": "写数学作业",
    },
    {
        "name": "02-刚才调代码",
        "when": "recent",
        "understanding": {
            "scene": "电脑桌前",
            "activity": "调试 Python 程序",
            "objects": ["笔记本电脑", "显示器", "键盘"],
            "description": "用户正在电脑上调试 Python 代码，屏幕上是编辑器",
            "importance": 0.6,
            "facts": ["用户在写 Python 程序"],
        },
        "query": "刚刚我在做什么",
        "expect": "调试 Python 代码",
    },
    {
        "name": "03-今天背单词",
        "when": "today",
        "understanding": {
            "scene": "书桌",
            "activity": "背英语单词",
            "objects": ["单词书", "手机", "笔记"],
            "description": "用户拿着单词书背英语单词",
            "importance": 0.4,
            "facts": ["用户在准备英语考试"],
        },
        "query": "今天我学习了什么",
        "expect": "背英语单词",
    },
    {
        "name": "04-今天吃早饭",
        "when": "today",
        "understanding": {
            "scene": "餐厅",
            "activity": "吃早饭",
            "objects": ["豆浆", "包子", "碗筷"],
            "description": "用户在餐桌前吃早饭，桌上有豆浆和包子",
            "importance": 0.3,
            "facts": [],
        },
        "query": "今天我吃了什么",
        "expect": "吃早饭",
    },
    {
        "name": "05-昨天跑步",
        "when": "yesterday",
        "understanding": {
            "scene": "小区附近的马路",
            "activity": "跑步锻炼",
            "objects": ["运动鞋", "耳机", "路灯"],
            "description": "用户傍晚在马路上跑步锻炼",
            "importance": 0.4,
            "facts": ["用户有跑步的习惯"],
        },
        "query": "昨天我做了什么运动",
        "expect": "跑步",
    },
    {
        "name": "06-昨天看电影",
        "when": "yesterday",
        "understanding": {
            "scene": "客厅",
            "activity": "看电影",
            "objects": ["电视", "沙发", "爆米花"],
            "description": "用户晚上在沙发上看电影",
            "importance": 0.3,
            "facts": [],
        },
        "query": "昨天晚上我在干嘛",
        "expect": "看电影",
    },
    {
        "name": "07-最近感冒",
        "when": "3days",
        "understanding": {
            "scene": "卧室",
            "activity": "量体温休息",
            "objects": ["体温计", "纸巾", "水杯"],
            "description": "用户有点感冒，正在量体温并卧床休息",
            "importance": 0.8,
            "facts": ["用户最近身体不舒服"],
        },
        "query": "最近我的身体怎么样",
        "expect": "感冒",
    },
    {
        "name": "08-最近玩游戏",
        "when": "recent",
        "understanding": {
            "scene": "电脑前",
            "activity": "玩原神",
            "objects": ["游戏手柄", "显示器", "耳机"],
            "description": "用户在电脑上玩原神做每日任务",
            "importance": 0.3,
            "facts": ["用户玩原神"],
        },
        "query": "我最近玩了什么游戏",
        "expect": "原神",
    },
    {
        "name": "09-今天处理表格",
        "when": "today",
        "understanding": {
            "scene": "书桌",
            "activity": "用 Excel 处理文件",
            "objects": ["笔记本电脑", "Excel", "文件"],
            "description": "用户在用 Excel 处理文件，做数据统计",
            "importance": 0.5,
            "facts": [],
        },
        "query": "今天我处理了什么文件",
        "expect": "Excel",
    },
    {
        "name": "10-上次在食堂",
        "when": "yesterday",
        "understanding": {
            "scene": "学校食堂",
            "activity": "吃午饭",
            "objects": ["餐盘", "米饭", "同学"],
            "description": "用户中午在食堂吃午饭，和同学坐一桌",
            "importance": 0.3,
            "facts": ["用户在学校吃饭"],
        },
        "query": "上次我在哪里吃的饭",
        "expect": "食堂",
    },
    {
        "name": "11-整理房间",
        "when": "recent",
        "understanding": {
            "scene": "卧室",
            "activity": "整理房间",
            "objects": ["衣柜", "收纳箱", "拖把"],
            "description": "用户在整理房间，把衣服叠好放进收纳箱",
            "importance": 0.4,
            "facts": [],
        },
        "query": "我在干什么",
        "expect": "整理房间",
    },
    {
        "name": "12-今天逛超市",
        "when": "today",
        "understanding": {
            "scene": "超市",
            "activity": "推着购物车买东西",
            "objects": ["购物车", "牛奶", "面包"],
            "description": "用户在超市里推着购物车买牛奶和面包",
            "importance": 0.4,
            "facts": [],
        },
        "query": "今天我买了什么",
        "expect": "超市",
    },
    {
        "name": "13-昨天和朋友聊天",
        "when": "yesterday",
        "understanding": {
            "scene": "学校走廊",
            "activity": "和朋友聊天",
            "objects": ["同学", "书包"],
            "description": "用户放学后和朋友在走廊聊天",
            "importance": 0.3,
            "facts": [],
        },
        "query": "昨天我和谁聊过天",
        "expect": "朋友",
    },
    {
        "name": "14-刚才调摄像头",
        "when": "recent",
        "understanding": {
            "scene": "电脑桌前",
            "activity": "调试摄像头",
            "objects": ["摄像头", "USB线", "笔记本电脑"],
            "description": "用户正在调试摄像头，接线后画面打不开",
            "importance": 0.7,
            "facts": ["用户的摄像头有访问问题"],
        },
        "query": "刚才有什么问题没解决",
        "expect": "摄像头",
    },
    {
        "name": "15-今天读小说",
        "when": "today",
        "understanding": {
            "scene": "窗边",
            "activity": "读小说",
            "objects": ["纸质书", "咖啡", "椅子"],
            "description": "用户坐在窗边读小说放松",
            "importance": 0.3,
            "facts": [],
        },
        "query": "今天有什么休闲活动",
        "expect": "读小说",
    },
    {
        "name": "16-最近去健身房",
        "when": "3days",
        "understanding": {
            "scene": "健身房",
            "activity": "举铁锻炼",
            "objects": ["哑铃", "跑步机", "毛巾"],
            "description": "用户在健身房举铁锻炼",
            "importance": 0.5,
            "facts": ["用户最近在健身"],
        },
        "query": "最近我去过哪里锻炼",
        "expect": "健身房",
    },
    {
        "name": "17-提到作业",
        "when": "today",
        "understanding": {
            "scene": "书桌",
            "activity": "抄写作业答案",
            "objects": ["作业本", "平板电脑"],
            "description": "用户在抄写作业答案，作业很多",
            "importance": 0.5,
            "facts": ["用户的作业量不小"],
        },
        "query": "和作业有关的记忆有哪些",
        "expect": "作业",
    },
    {
        "name": "18-昨天做饭",
        "when": "yesterday",
        "understanding": {
            "scene": "厨房",
            "activity": "做晚饭",
            "objects": ["炒锅", "青菜", "燃气灶"],
            "description": "用户在厨房做晚饭，正在炒青菜",
            "importance": 0.4,
            "facts": ["用户会自己做饭"],
        },
        "query": "昨天晚饭是怎么解决的",
        "expect": "做晚饭",
    },
    {
        "name": "19-今天骑车",
        "when": "today",
        "understanding": {
            "scene": "马路边",
            "activity": "骑自行车通勤",
            "objects": ["自行车", "头盔", "红绿灯"],
            "description": "用户骑自行车上学通勤，正在等红绿灯",
            "importance": 0.4,
            "facts": ["用户骑车通勤"],
        },
        "query": "今天我是怎么出行的",
        "expect": "骑自行车",
    },
    {
        "name": "20-刚才喝咖啡",
        "when": "recent",
        "understanding": {
            "scene": "咖啡店",
            "activity": "喝咖啡",
            "objects": ["咖啡杯", "手机", "小圆桌"],
            "description": "用户在咖啡店喝咖啡休息",
            "importance": 0.3,
            "facts": [],
        },
        "query": "刚才我喝了什么",
        "expect": "咖啡",
    },
]
